package com.ryl.myandroidlibdemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ryl.myandroidlibdemo.testbean.Provinces;

import com.ryl.myandroidlibdemo.db.ProvincesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig provincesDaoConfig;

    private final ProvincesDao provincesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        provincesDaoConfig = daoConfigMap.get(ProvincesDao.class).clone();
        provincesDaoConfig.initIdentityScope(type);

        provincesDao = new ProvincesDao(provincesDaoConfig, this);

        registerDao(Provinces.class, provincesDao);
    }
    
    public void clear() {
        provincesDaoConfig.clearIdentityScope();
    }

    public ProvincesDao getProvincesDao() {
        return provincesDao;
    }

}
